### ISSUE TITLE
[1.x] cannot login to SBA Server

### ISSUE THREAD

**Issue by paulvi** [vojtechruz/spring-boot-admin#8]
With current code (Spring Security config) for 1.x branch

it is not possible to open system, `/login` is broken:

![image](https://user-images.githubusercontent.com/1614482/51072365-8eea3880-169a-11e9-8b2a-5cc3cba17d40.png)

yes, `server.port=9000` has been added to `application.properties`

**Comment by vojtechruz** [comment]
Can you try now please?

**Comment by paulvi** [comment]
There is some issue with Spring Security

disable loginPage configuration helps

```java
.formLogin() //.loginPage("/login").successHandler(successHandler)
```

**Comment by paulvi** [comment]
c632d8a5de2ef6e74edcb3bd785467bdfd97f7a0 

has this issue and many other solved.
